var AppConstants = {
    ROOMS_FETCHED : 'ROOMS_FETCHED',
    CREATE_ROOM : 'CREATE_ROOM',
    DELETE_ROOM : 'DELETE_ROOM',
    MESSAGES_FETCHED : 'MESSAGES_FETCHED',
    NEW_MESSAGE_FETCHED : 'ONE_MESSAGE_FETCHED',
};

module.exports = AppConstants;