var AppConstants = {
    CREATE_ROOM : 'CREATE_ROOM',
    DELETE_ROOM : 'DELETE_ROOM',
    ROOM_LIST_FETCHED : 'ROOM_LIST_FETCHED',
    ROOM_MESSAGES_FETCHED : 'ROOM_MESSAGES_FETCHED',
    NEW_MESSAGE_FETCHED : 'NEW_MESSAGE_FETCHED',
};

module.exports = AppConstants;