var AppConstants = {
    USER_FETCHED : 'USER_FETCHED',
    CREATE_ROOM : 'CREATE_ROOM',
    DELETE_ROOM : 'DELETE_ROOM',
    ROOM_LIST_FETCHED : 'ROOM_LIST_FETCHED',
    MESSAGE_FETCHED : 'MESSAGE_FETCHED',
    MESSAGE_REMOVED : 'MESSAGE_REMOVED',
    MEMBERS_FETCHED : 'MEMBERS_FETCHED'
};

module.exports = AppConstants;